### ISSUE TITLE
Mint coin DRC 20

### ISSUE THREAD

**Issue by Khoiwall** [zachzwei/doggy_x1#1]
![Screenshot 2024-02-27 172930](https://github.com/zachzwei/doggy_x1/assets/58501570/d3d05ccf-8abd-4e21-860a-8d723f2131e2)

node . drc-20 mint D6RdLnFbwLdgUkPUEsQ3jdePHn4MPrgag5 wen 100000000
inscription txid: 90ccddd72ca26ab1deefaeda05879c21a5c141df19ce5bf1eb7cb4aedf365c70

When I mint it, the above result appears. After minting, it will automatically return to the wallet that I assigned in the node command. Mint, right?

But I copied the txid and added it to doge scan but couldn't find the Transaction

@zachzwei

**Comment by zachzwei** [comment]
this is a known issue when minting tickers with special characters
use '$wen' instead of just wen

**Comment by Khoiwall** [comment]
@zachzwei 
![image](https://github.com/zachzwei/doggy_x1/assets/58501570/1a10e71d-c720-4b27-ad89-e47809cd7c17)

I dump it

---

But I don't use node like you but use api

![20240227-213410](https://github.com/zachzwei/doggy_x1/assets/58501570/425e191b-63a2-4bd3-b4ca-f7d4c9f7e118)

---

I don't know if I'm doing it right, but there are some Transactions that can't find a block :(((. This is due to low gas or an error.

![image](https://github.com/zachzwei/doggy_x1/assets/58501570/d90867f8-8ada-48d2-9631-137ff266b882)

**Comment by zachzwei** [comment]
probably low gas combined with the current status of Doge
188K pending atm

**Comment by Khoiwall** [comment]
![image](https://github.com/zachzwei/doggy_x1/assets/58501570/df391ed9-ade4-495e-9fdb-8212e9a0d787)
I set gas :((((. But it's probably too low, I'll set FEE_PER_KB = 5000000

**Comment by zachzwei** [comment]
set it to at least 100000000

**Comment by Khoiwall** [comment]
@zachzwei Can you air for me 1-2 NFT natdoges ?
my address DFE1LFTg5e22TVa5FtKq3EEJmk1swgUaBw
thank you so muchhhhhh ^^
